config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'homepage#home', as: "root"
  get 'download_resume', to: 'homepage#download_resume'
  get '*path' => redirect('/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  require 'open-uri'
  require 'json'

  def home
  	@firstimgs = scrape_first_imgs.shuffle!
  	@restimgs = scrape_rest_imgs.shuffle!
  	@quotes = scrape_quotes.shuffle!
  	@index = 0
  end

  def download_resume
  	send_file "public/Juwon_Cha_Resume.pdf", type: "application/pdf", x_sendfile: true
  end

  #github.com/saadq
  def scrape_first_imgs
    url = "https://reddit.com/r/earthporn/top.json?sort=top&t=all&limit=1000&before=t3_6vz211"
    res = open(url, "User-Agent" => "Ruby/#{RUBY_VERSION}").read
    reddit_json = JSON.parse(res)

    images = []

    reddit_json['data']['children'].length.times do |n|
      img = {
        title:    reddit_json['data']['children'][n]['data']['title'],
        img_url:  reddit_json['data']['children'][n]['data']['url'],
        post_url: reddit_json['data']['children'][n]['data']['permalink'],
        width: reddit_json['data']['children'][n]['data']['preview']['images'][0]['source']['width']
      }

      if valid_img?(img) && img[:width] > 1500 && !img[:title].include?("tulips") && !img[:title].include?("Texas") && !img[:title].include?("Phases") 

        normalize_url(img[:img_url])
        images << img
      end
    end

    images
  end

  def scrape_quotes
    url = "https://reddit.com/r/todayilearned/top.json?sort=top&t=all&limit=1000"
    res = open(url, "User-Agent" => "Ruby/#{RUBY_VERSION}").read
    reddit_json = JSON.parse(res)

    quotes = []

    reddit_json['data']['children'].length.times do |n|
      quote = {
        title:    reddit_json['data']['children'][n]['data']['title'],
        post_url: reddit_json['data']['children'][n]['data']['permalink']
      }

      normalize_title(quote)
      if quote[:title].length < 270
      	quotes<<quote
      end
    end

    scrape_more_quotes.each do |quote|
    	quotes<<quote
    end
    quotes
  end

  def scrape_more_quotes
  	url = "https://www.reddit.com/r/todayilearned/top.json?sort=top&t=all&limit=100&after=t3_axrxwf"
  	res = open(url, "User-Agent" => "Ruby/#{RUBY_VERSION}").read
    reddit_json = JSON.parse(res)

    quotes = []

    reddit_json['data']['children'].length.times do |n|
      quote = {
        title:    reddit_json['data']['children'][n]['data']['title'],
        post_url: reddit_json['data']['children'][n]['data']['permalink']
      }

      normalize_title(quote)
      if quote[:title].length < 270
      	quotes<<quote
      end
    end

    quotes
  end

  def scrape_rest_imgs
    url = "https://reddit.com/r/earthporn/top.json?sort=top&t=all&limit=1000&after=t3_6vz211"
    res = open(url, "User-Agent" => "Ruby/#{RUBY_VERSION}").read
    reddit_json = JSON.parse(res)

    images = []

    reddit_json['data']['children'].length.times do |n|
      img = {
        title:    reddit_json['data']['children'][n]['data']['title'],
        img_url:  reddit_json['data']['children'][n]['data']['url'],
        post_url: reddit_json['data']['children'][n]['data']['permalink'],
        width: reddit_json['data']['children'][n]['data']['preview']['images'][0]['source']['width']

      }

      if valid_img?(img) && img[:width] > 1800
        normalize_url(img[:img_url])
        images << img
      end
    end

    scrape_more_images.each do |img|
    	images<<img
    end
    images
  end

  def scrape_more_images
  	url = "https://reddit.com/r/earthporn/top.json?sort=top&t=all&limit=1000&after=t3_7whpvs"
    res = open(url, "User-Agent" => "Ruby/#{RUBY_VERSION}").read
    reddit_json = JSON.parse(res)

    images = []

    reddit_json['data']['children'].length.times do |n|
      img = {
        title:    reddit_json['data']['children'][n]['data']['title'],
        img_url:  reddit_json['data']['children'][n]['data']['url'],
        post_url: reddit_json['data']['children'][n]['data']['permalink'],
        width: reddit_json['data']['children'][n]['data']['preview']['images'][0]['source']['width']

      }

      if valid_img?(img) && img[:width] > 1800
        normalize_url(img[:img_url])
        images << img
      end
    end

    images
  end

  def normalize_title(quote)
  	quote[:title] = quote[:title][4..]
	if quote[:title][0] == ' ' || quote[:title][0] == ":"
		quote[:title] = quote[:title][1..]
	end
  	if quote[:title][0..3] == 'that'
  		quote[:title] = quote[:title][5..]
  	end
  	if quote[:title][0] == " " || quote[:title][0] == ":"
  		quote[:title] = quote[:title][1..]
  	end
  	quote[:title][0] = quote[:title][0].upcase
  	length = quote[:title].length
  	if quote[:title][length - 1] != "." && quote[:title][length - 2] != "."
  		quote[:title] << "."
  	end
  	if quote[:title][0..1] == "Of"
  		quote[:title] = quote[:title][3..]
  		quote[:title][0] = quote[:title][0].upcase
  	end
  end

  # Checks to see if the image url is an
  # imgur link and that it is only a single image
  def valid_img?(img)
    img != nil &&
    !img.empty? &&
    (imgur?(img) || ireddit?(img))
  end

  # Checks to see if the image url is an imgur link
  def imgur?(img)
    img[:img_url][7..11] == 'imgur' ||
    img[:img_url][7..11] == 'i.img' ||
    img[:img_url][7..11] == 'm.img'
  end

  # Checks to see if the image url is an ireddit link
  def ireddit?(img)
    img[:img_url][8..16] == 'i.redd.it'
  end

  # Normalizes an imgur url to start with i.imgur
  def normalize_url(img_url)
    if img_url[7..11] == 'imgur'
      img_url.insert(7, 'i.')
      img_url << ".jpg"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/homepage/home.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Juwon Cha</title>
		<%= csrf_meta_tags %>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>
	<body>
		<div class="container">
			<header class="navbar navbar-fixed-top navbar-inverse">
		      <div class="container">
		        <%= link_to "Juwon Cha", root_path, id: "logo" %>
		        <nav>
		          <ul class="nav navbar-nav navbar-right">
		            <li><%= link_to "About Me", '#aboutme', 'data-toggle' => 'modal' %></li>
		            <li><%= link_to "Projects", '#projects', 'data-toggle' => 'modal'%></li>
		            <li><%= link_to "Resume", '#downloadresume', 'data-toggle' => 'modal' %></li>
		          </ul>
		        </nav>
		      </div>
		    </header>
		    <div class="centered">
		    	<h1 class = "rellax" data-rellax-speed="-3">Human. Nature.</h1>
		    </div>
		</div>
		<script src="rellax.js"></script>
		<script>
		  // Accepts any class name
		  var rellax = new Rellax('.rellax', {
    		center: true
  		  });
		</script>
		<div class = "container">
		<div class = "movedown">
			<div id =  "quotess">
				<% @quotes.each do |quote| %>
					<script>
						var quotetext = '<%= quote[:title] %>';
						var quotelink = '<%= quote[:post_url] %>';
						appenddiv(quotetext, quotelink);
					</script>
				<% end %>
			</div>
		</div>
	</div>
	</body>
	<% @firstimgs.each do |img| %>
		<div>
			<%= link_to image_tag("#{img[:img_url]}", class: "img-fluid" ), "http://reddit.com/#{img[:post_url]}" %>
		</div>
	<% end %>
	<% @restimgs.each do |img| %>
		<%= link_to image_tag("#{img[:img_url]}", data: {src: "#{img[:img_url]}"}, class: "img-fluid lazy"), "http://reddit.com/#{img[:post_url]}" %>
	<% end %>
	<script src="rellax.js"></script>
		<script>
		  // Accepts any class name
		  var rellax = new Rellax('.rellax', {
    		center: true
  		  });
		</script>
		<div class="modal fade bd-example-modal-lg" id="aboutme" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
		  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <h4 class="modal-title text-primary" id="ModalCenterTitle">About Me</h4>
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
		          <span aria-hidden="true">&times;</span>
		        </button>
		      </div>
			  <div class="modal-body">
			        <p class="indent">  With a long history of entrepreneurial endeavors and after graduating with four majors, I set out to study computer science. Within a year of studying the exact same coursework, projects, and exams a UC Berkeley CS student would have taken, I have built a few personal Ruby on Rails apps, contributed to open source projects, and am ready to take on a full-time job.</p>

			       	<p class = "indent">   I am driven, adaptable, having a variety of experiences from many different areas of industry. I can't wait to learn more, join an impactful team, and help a company succeed. (P.S. This site was built from the ground up by me. Scroll down and learn something cool today!)</p>
			  </div>
		      <div class="modal-footer">
		      	 <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
		    </div>
		  </div>
		</div>
	</div>
	<div class="modal fade" id="downloadresume" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h4 class="modal-title text-primary">Download Resume</h4>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>
	      <div class="modal-body">
	        Would you like to proceed with your download?
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
	        <button type="button" class="btn btn-primary"><%= link_to "PDF", download_resume_path %></button>
	      </div>
	    </div>
	  </div>
	</div>
	<div class="modal fade" id="projects" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <h4 class="modal-title text-primary">Github Projects</h4>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div>
	      <div class="modal-body">
	        Would you like to proceed to github and check out my projects?
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
	        <button type="button" class="btn btn-primary"><%= link_to "Github", 'https://github.com/dustmop44' %></button>
	      </div>
	    </div>
	  </div>
	</div>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyPortfolioSite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>